'use strict';
document.documentElement.classList.add('js');
const projects=window.PROJECTS, grid=document.querySelector('#projects-grid'), dialog=document.querySelector('#project-dialog');
let activeIndex=0, opener=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
grid.innerHTML=projects.map((p,i)=>`<article class="project-card" data-id="${p.id}" data-category="${p.category}"><button data-project="${i}" aria-label="Explore ${esc(p.title)}"><div class="project-image"><img src="assets/${p.image}" alt="${esc(p.alt)}" loading="lazy" width="800" height="640"><span class="project-number">0${i+1}</span><span class="project-open" aria-hidden="true">↗</span></div><div class="project-meta"><span>${esc(p.label)}</span><span>${esc(p.year)}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.subtitle)}</p></button></article>`).join('');
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));let count=0;document.querySelectorAll('.project-card').forEach(c=>{c.hidden=b.dataset.filter!=='All'&&c.dataset.category!==b.dataset.filter;if(!c.hidden)count++});document.querySelector('#project-count').textContent=`Showing ${count} projects`; }));
function renderProject(index){activeIndex=(index+projects.length)%projects.length;const p=projects[activeIndex];document.querySelector('#dialog-index').textContent=`SELECTED WORK / 0${activeIndex+1} OF 0${projects.length}`;document.querySelector('#project-content').innerHTML=`<span class="micro">${esc(p.label)} / ${esc(p.year)}</span><h2 id="project-title">${esc(p.title)}</h2><p class="project-intro">${esc(p.intro)}</p><div class="tags">${p.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><img class="dialog-hero" src="assets/${p.image}" alt="${esc(p.alt)}"><div class="case-sections">${[['My contribution',p.contribution],['How it works',p.approach],['What I learned',p.learning],['The outcome',p.outcome]].map(([h,t])=>`<section><h3>${h}</h3><p>${esc(t)}</p></section>`).join('')}</div>${p.gallery.length?`<div class="case-gallery">${p.gallery.map((f,i)=>`<figure class="gallery-item ${f.wide?'wide':''}"><a href="assets/${esc(f.src)}" target="_blank" rel="noopener" aria-label="View full-size: ${esc(f.caption)}"><img loading="lazy" src="assets/${esc(f.src)}" alt="${esc(f.caption)}"></a><figcaption><span>${esc(f.caption)}</span><a href="assets/${esc(f.src)}" target="_blank" rel="noopener">View full size ↗</a></figcaption></figure>`).join('')}</div>`:''}<div class="case-links">${p.links.map(([label,url])=>`<a class="text-link" href="${url}" target="_blank" rel="noopener">${esc(label)} <span>↗</span></a>`).join('')}</div>`;dialog.scrollTop=0;}
grid.addEventListener('click',e=>{const b=e.target.closest('[data-project]');if(!b)return;opener=b;renderProject(Number(b.dataset.project));dialog.showModal();document.body.classList.add('modal-open');document.querySelector('#close-project').focus();});
function closeProject(){dialog.close();}
document.querySelector('#close-project').addEventListener('click',closeProject);dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');opener?.focus()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeProject()}});
document.querySelector('#prev-project').addEventListener('click',()=>renderProject(activeIndex-1));document.querySelector('#next-project').addEventListener('click',()=>renderProject(activeIndex+1));
const menu=document.querySelector('.menu-toggle'), mobileNav=document.querySelector('#mobile-nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));mobileNav.hidden=!open;menu.querySelector('span').textContent=open?'−':'+'});mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileNav.hidden=true;menu.setAttribute('aria-expanded','false');menu.querySelector('span').textContent='+'}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!mobileNav.hidden){mobileNav.hidden=true;menu.setAttribute('aria-expanded','false');menu.querySelector('span').textContent='+';menu.focus()}});
document.querySelector('#copy-email').addEventListener('click',async()=>{const s=document.querySelector('#copy-status');try{await navigator.clipboard.writeText('o.liang@mail.utoronto.ca');s.textContent='COPIED';setTimeout(()=>s.textContent='',2500)}catch{ s.textContent='SELECT THE EMAIL ABOVE TO COPY';}});
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('pending');observer.unobserve(e.target)}})},{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('pending');observer.observe(el)});}
